//require("./memoize");
//require("./object-value-by-key-path");
//require("./remove-array-duplicates");
//require("./remove-duplicate-chars");
//require("./array-intersection");
//require("./promise-mess");
//require("./pascal-triangle");
//require("./binary-tree-sum");
require("./is-palindrome");
